from dataclasses import dataclass
from typing import Dict, List
from backend.app.models import ManipulationCategory


@dataclass(frozen=True)
class TacticDefinition:
    category: ManipulationCategory
    name: str
    description: str
    severity_weight: float  # 0.0 to 1.0 multiplier for risk engine
    anchor_phrases: List[str]


# Source of truth taxonomy for RAKSHA manipulation detection
TACTIC_REGISTRY: Dict[ManipulationCategory, TacticDefinition] = {
    ManipulationCategory.URGENCY: TacticDefinition(
        category=ManipulationCategory.URGENCY,
        name="Urgency & Time Pressure",
        description="Inducing panic by imposing an artificial, immediate deadline to bypass rational thinking.",
        severity_weight=0.75,
        anchor_phrases=[
            "You must act immediately or face severe penalties",
            "There is a warrant active right now and time is running out",
            "Within the next 15 minutes your account will be permanently blocked",
            "Do not delay, every second counts right now",
            "Immediate action required before the system locks down",
            "You only have a few minutes to resolve this urgent matter",
            "You have only 15 minutes",
            "You must act within 2 minutes or your accounts will be seized",
            "Aapko abhi turant action lena hoga nahi to account block ho jayega",
            "Only ten minutes left before your SIM card and line is disconnected",
            "Abhi turant OTP verify kijiye warna account block ho jayega",
            "Nimma account block agutte, immediate verification agabeku",
            "Iga immediate action madbeku, illadiddare account lock agutte",
            "Ventane verify cheyyali, lekapothe account block avutundi",
            "మీ account block అవుతుంది, urgent ga update cheyandi",
            "आपका बैंक खाता तुरंत ब्लॉक कर दिया जाएगा, अभी वेरिफिकेशन करें",
            "Urgent KYC update required within 5 minutes or banking services suspended",
        ],
    ),
    ManipulationCategory.AUTHORITY_IMPERSONATION: TacticDefinition(
        category=ManipulationCategory.AUTHORITY_IMPERSONATION,
        name="Authority Impersonation",
        description="Falsely claiming to be law enforcement, government officials, or bank fraud departments.",
        severity_weight=0.90,
        anchor_phrases=[
            "This is Officer Miller from the Federal Police Department",
            "Calling from the Central Bank fraud investigation team",
            "This is the cybercrime division investigating your identity",
            "I am the federal tax inspector handling your arrest warrant",
            "This is customs and border protection narcotics division",
            "I am a special agent with the national security agency",
            "This is Special Agent Vance from the Cybercrime Investigation Bureau",
            "This is Officer Miller from the Federal Tax Police",
            "This is Special Agent Officer Davis calling from the Federal Bureau of Investigation Fraud Department",
            "This is Officer Smith from IRS",
            "This is Federal Officer Brown",
            "This is Officer Jones",
            "Main Mumbai Police Crime Branch se Officer Sharma bol raha hu",
            "This is CBI digital arrest officer calling regarding your illegal parcel",
            "Calling from Telecom Regulatory Authority of India fraud department",
            "Nanu Cyber Crime Police Station ninda matnadtidini, nimma hesaralli complaint ide",
            "Nenu High Court crime branch officer matladutunnanu",
            "Main RBI verification department se senior manager bol raha hu",
            "நாcopotics control bureau லிருந்து பேசுகிறேன்",
            "Sir nenu bank senior officer, your account security audit is in progress",
            "നർക്കോട്ടിക്സ് കൺട്രോൾ ബ്യൂറോയിൽ നിന്നാണ് സംസാരിക്കുന്നത്",
        ],
    ),
    ManipulationCategory.ISOLATION_SECRECY: TacticDefinition(
        category=ManipulationCategory.ISOLATION_SECRECY,
        name="Isolation & Secrecy",
        description="Coercing the victim into secrecy, cutting off family members, or demanding continuous line presence.",
        severity_weight=0.85,
        anchor_phrases=[
            "Do not hang up this call or we will dispatch officers",
            "You cannot discuss this with anyone, including your family",
            "This is a confidential national security matter, keep it secret",
            "Stay on the line with me, do not disconnect or tell anyone",
            "Go into a private room where no one can overhear our conversation",
            "Do not mention this conversation to your children or spouse",
            "you cannot tell your family or disconnect this line",
            "Call disconnect mat karna warna police aapke ghar pahunch jayegi",
            "Kisi ko mat batana, yeh ek confidential government investigation hai",
            "Yara hatramnu matnadabeda, call cut madbaradu",
            "Evari tho cheppakandi, line cut chesthe immediate arrest untundi",
            "Ghar me kisi ko mat batana, don't tell your family members",
            "Nimma family ge helabeda, stay on the line until investigation completes",
            "ఎవరికీ చెప్పకండి, ఇది రహస్య పరిశోధన",
            "Do not cut the call or inform your bank branch manager",
        ],
    ),
    ManipulationCategory.FINANCIAL_REDIRECTION: TacticDefinition(
        category=ManipulationCategory.FINANCIAL_REDIRECTION,
        name="Financial Redirection & Unorthodox Payments",
        description="Demanding funds via gift cards, crypto kiosks, wire transfers, or remote access tools.",
        severity_weight=0.95,
        anchor_phrases=[
            "Purchase Apple or Target gift cards to verify and safeguard your funds",
            "Transfer your savings to the secure government safety locker account",
            "Download AnyDesk or TeamViewer so I can secure your workstation",
            "Deposit cash at the Bitcoin ATM terminal immediately",
            "Send money through wire transfer or crypto to protect your balance",
            "Withdraw all cash from your bank and deposit it into the federal escrow account",
            "transfer your funds to our secure safety account",
            "wire $5,000 to our safe holding account immediately",
            "Wire $5,000 to our safe account immediately",
            "Wire $5,000 to our government safety account right now",
            "Aapka sara paisa RBI safety account mein UPI ya RTGS se transfer karo",
            "Download AnyDesk app immediately so we can verify and unblock your account",
            "Nimma ella hano government safety locker account ge transfer maadi",
            "Mee money motham RBI safe account ki UPI dwara transfer cheyandi",
            "Apka saara balance RBI safety account me UPI transfer kijiye",
            "Download RustDesk or TeamViewer QuickSupport for remote KYC verification",
            "உங்கள் பணத்தை பாதுகாப்பு கணக்கிற்கு உடனடியாக மாற்றவும்",
            "UPI PIN enter madi refund receive madi",
        ],
    ),
    ManipulationCategory.FEAR_INTIMIDATION: TacticDefinition(
        category=ManipulationCategory.FEAR_INTIMIDATION,
        name="Fear & Intimidation",
        description="Direct coercion using threats of arrest, asset forfeiture, deportation, or criminal prosecution.",
        severity_weight=0.90,
        anchor_phrases=[
            "Police are already outside your house to take you into custody",
            "An arrest warrant has been issued in your name for criminal fraud",
            "Your passport and citizenship will be revoked immediately",
            "All your bank accounts and property have been frozen and confiscated",
            "You will be arrested and put in federal prison if you do not comply",
            "You will face severe criminal charges and jail time",
            "face instant arrest",
            "or you will be arrested",
            "to stop arrest",
            "to prevent arrest",
            "Aapke naam par arrest warrant issue ho gaya hai aur police bhej rahe hain",
            "Your Aadhaar card is linked to money laundering and drug smuggling",
            "Nimma Aadhaar card illegal money laundering case nalli involve agide",
            "Mee Aadhaar card narcotics and human trafficking case lo link ayindi",
            "Police team aapke ghar par aane wali hai, arrest warrant ready hai",
            "మీపై అరెస్ట్ వారెంట్ జారీ చేయబడింది, వెంటనే చర్య తీసుకోండి",
            "Your bank account has been frozen due to suspicious illegal activity",
        ],
    ),
    ManipulationCategory.INFORMATION_PHISHING: TacticDefinition(
        category=ManipulationCategory.INFORMATION_PHISHING,
        name="Information & Credential Phishing",
        description="Extracting sensitive authentication data, OTPs, CVVs, passwords, or identity numbers.",
        severity_weight=0.80,
        anchor_phrases=[
            "Read me the 6-digit one-time password OTP you just received",
            "Tell me the verification number that came to your phone",
            "Read the six digit security code sent by SMS to your mobile device",
            "Confirm your full Social Security number and date of birth",
            "Provide the 3-digit CVV security code on the back of your card",
            "What is your online banking username and login password",
            "Give me your 6-digit verification OTP passcode sent to your cell phone",
            "Give me your 6-digit OTP code right now",
            "Aapke phone par jo 6 digit OTP aaya hai turant bataiye",
            "Confirm your Aadhaar number and debit card PIN for verification",
            "OTP abhi bataiye turant",
            "OTP helu, fast ga verify madonam",
            "OTP cheppandi, ippude account unblock chestam",
            "Please share the OTP sent to your registered mobile number",
            "Nimma debit card number mathe CVV heli",
            "Mee phone ki vachina 6-digit verification code ventane cheppandi",
            "ನಿಮ್ಮ ఫోణަށް ಬಂದ OTP ಸಂಖ್ಯೆಯನ್ನು వెంటనే చెప్పండి",
        ],
    ),
    ManipulationCategory.CONFUSION_OVERWHELM: TacticDefinition(
        category=ManipulationCategory.CONFUSION_OVERWHELM,
        name="Cognitive Overwhelm",
        description="Flooding the victim with rapid legal jargon, confusing citations, or contradictory steps.",
        severity_weight=0.60,
        anchor_phrases=[
            "Section 420 of the penal code clause 8 mandates immediate compliance",
            "Your IP address was routed through a darknet syndicate node",
            "The ledger mismatch requires real-time forensic cache validation",
            "Federal statute requires instantaneous algorithmic escrow indemnification",
            "The international anti-money laundering protocol necessitates server re-authorization",
            "We detected a severe security breach on your computer right now",
            "IPC Section 420 ke tehat digital custody warrant issue hua hai",
            "PML Act Section 3 mathe 4 prakara digital custody warrant generate agide",
            "IT Act Section 66A and IPC Section 420 tehat legal proceedings start ayindi",
            "Cyber cell protocol 9B under aapka biometric checksum mismatch hua hua hai",
            "RBI circular 2024 compliance policy section 14 under account audit required",
        ],
    ),
    ManipulationCategory.RELIEF_FALSE_SALVATION: TacticDefinition(
        category=ManipulationCategory.RELIEF_FALSE_SALVATION,
        name="Relief & False Salvation",
        description="Positioning the scammer as the victim's sole ally or protector against imminent disaster.",
        severity_weight=0.70,
        anchor_phrases=[
            "I am the only person trying to protect you from being arrested",
            "I am the only one who can help clear your name and resolve this investigation",
            "Work with me and I will ensure your name is cleared today",
            "If you follow my instructions carefully, you will not get in trouble",
            "Do not worry, as long as you cooperate with me you are safe",
            "I am here to help you resolve this mess before the officers arrive",
            "Main aapki help kar raha hu taaki aap arrest na ho, meri baat suniye",
            "Nanu nimage help madtidini arrest agbardu anta, nanna maatu keli",
            "Nenu meeku sahayama chestunanu arrest kakunda, nenu cheppindi vinandi",
            "Main aapko court case se bacha raha hu, bas mera instruction follow karo",
            "Cooperate with me and I will clear your name from the CBI suspect list",
        ],
    ),
}
